# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ["8.0.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore ./Minimal.Api/Minimal.Api.csproj

      - name: Build
        run: dotnet build ./Minimal.Api/Minimal.Api.csproj -c Release --no-restore

      - name: Publish
        run: dotnet publish ./Minimal.Api/Minimal.Api.csproj -c Release -o ./publish --self-contained true /p:UseAppHost=true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: publish/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: publish/

      - name: Deploy publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish/
